/*
 * Copyright (C) 2007-2016 Siemens AG
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction, 
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION 
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/*******************************************************************
 *
 * @author Daniel.Peintner.EXT@siemens.com
 * @version 2016-10-20 
 * @contact Joerg.Heuer@siemens.com
 *
 * <p>Code generated by EXIdizer</p>
 * <p>Schema: exi4js.xsd.</p>
 *
 *
 ********************************************************************/



#ifndef EXI_EXIforJS_QNAMES_H
#define EXI_EXIforJS_QNAMES_H

#include "EXITypes.h"


/** Number of pre-populated qnames */
#define EXI_EXIforJSNUMBER_OF_PREPOPULATED_QNAMES 154

/** Number of runtime qnames */
#define EXI_EXIforJSMAX_NUMBER_OF_SUPPORTED_RUNTIMES_QNAMES 100

/** Number of overall qnames (pre-populated from schema and runtime qnames) */
#define EXI_EXIforJSMAX_NUMBER_OF_QNAMES (EXI_EXIforJSNUMBER_OF_PREPOPULATED_QNAMES + EXI_EXIforJSMAX_NUMBER_OF_SUPPORTED_RUNTIMES_QNAMES)

/** List of all qnames (and the associated qnameID) */
/* URI={} with uriID=0*/
/* URI={http://www.w3.org/XML/1998/namespace} with uriID=1*/
#define EXI_EXIforJS_1_base 0
#define EXI_EXIforJS_1_id 1
#define EXI_EXIforJS_1_lang 2
#define EXI_EXIforJS_1_space 3
/* URI={http://www.w3.org/2001/XMLSchema-instance} with uriID=2*/
#define EXI_EXIforJS_2_nil 0
#define EXI_EXIforJS_2_type 1
/* URI={http://www.w3.org/2001/XMLSchema} with uriID=3*/
#define EXI_EXIforJS_3_ENTITIES 0
#define EXI_EXIforJS_3_ENTITY 1
#define EXI_EXIforJS_3_ID 2
#define EXI_EXIforJS_3_IDREF 3
#define EXI_EXIforJS_3_IDREFS 4
#define EXI_EXIforJS_3_NCName 5
#define EXI_EXIforJS_3_NMTOKEN 6
#define EXI_EXIforJS_3_NMTOKENS 7
#define EXI_EXIforJS_3_NOTATION 8
#define EXI_EXIforJS_3_Name 9
#define EXI_EXIforJS_3_QName 10
#define EXI_EXIforJS_3_anySimpleType 11
#define EXI_EXIforJS_3_anyType 12
#define EXI_EXIforJS_3_anyURI 13
#define EXI_EXIforJS_3_base64Binary 14
#define EXI_EXIforJS_3_boolean 15
#define EXI_EXIforJS_3_byte 16
#define EXI_EXIforJS_3_date 17
#define EXI_EXIforJS_3_dateTime 18
#define EXI_EXIforJS_3_decimal 19
#define EXI_EXIforJS_3_double 20
#define EXI_EXIforJS_3_duration 21
#define EXI_EXIforJS_3_float 22
#define EXI_EXIforJS_3_gDay 23
#define EXI_EXIforJS_3_gMonth 24
#define EXI_EXIforJS_3_gMonthDay 25
#define EXI_EXIforJS_3_gYear 26
#define EXI_EXIforJS_3_gYearMonth 27
#define EXI_EXIforJS_3_hexBinary 28
#define EXI_EXIforJS_3_int 29
#define EXI_EXIforJS_3_integer 30
#define EXI_EXIforJS_3_language 31
#define EXI_EXIforJS_3_long 32
#define EXI_EXIforJS_3_negativeInteger 33
#define EXI_EXIforJS_3_nonNegativeInteger 34
#define EXI_EXIforJS_3_nonPositiveInteger 35
#define EXI_EXIforJS_3_normalizedString 36
#define EXI_EXIforJS_3_positiveInteger 37
#define EXI_EXIforJS_3_short 38
#define EXI_EXIforJS_3_string 39
#define EXI_EXIforJS_3_time 40
#define EXI_EXIforJS_3_token 41
#define EXI_EXIforJS_3_unsignedByte 42
#define EXI_EXIforJS_3_unsignedInt 43
#define EXI_EXIforJS_3_unsignedLong 44
#define EXI_EXIforJS_3_unsignedShort 45
/* URI={urn:javascript} with uriID=4*/
#define EXI_EXIforJS_4_ArrayExpression 0
#define EXI_EXIforJS_4_ArrayPattern 1
#define EXI_EXIforJS_4_ArrowExpression 2
#define EXI_EXIforJS_4_AssignmentExpression 3
#define EXI_EXIforJS_4_BinaryExpression 4
#define EXI_EXIforJS_4_BlockStatement 5
#define EXI_EXIforJS_4_BreakStatement 6
#define EXI_EXIforJS_4_CallExpression 7
#define EXI_EXIforJS_4_CatchClause 8
#define EXI_EXIforJS_4_ComprehensionExpression 9
#define EXI_EXIforJS_4_ConditionalExpression 10
#define EXI_EXIforJS_4_ContinueStatement 11
#define EXI_EXIforJS_4_DebuggerStatement 12
#define EXI_EXIforJS_4_Declaration 13
#define EXI_EXIforJS_4_DoWhileStatement 14
#define EXI_EXIforJS_4_EmptyStatement 15
#define EXI_EXIforJS_4_Expression 16
#define EXI_EXIforJS_4_ExpressionStatement 17
#define EXI_EXIforJS_4_ForInStatement 18
#define EXI_EXIforJS_4_ForOfStatement 19
#define EXI_EXIforJS_4_ForStatement 20
#define EXI_EXIforJS_4_FunctionDeclaration 21
#define EXI_EXIforJS_4_FunctionExpression 22
#define EXI_EXIforJS_4_GeneratorExpression 23
#define EXI_EXIforJS_4_GraphExpression 24
#define EXI_EXIforJS_4_GraphIndexExpression 25
#define EXI_EXIforJS_4_Identifier 26
#define EXI_EXIforJS_4_IfStatement 27
#define EXI_EXIforJS_4_LabeledStatement 28
#define EXI_EXIforJS_4_LetExpression 29
#define EXI_EXIforJS_4_LetStatement 30
#define EXI_EXIforJS_4_Literal 31
#define EXI_EXIforJS_4_LogicalExpression 32
#define EXI_EXIforJS_4_MemberExpression 33
#define EXI_EXIforJS_4_NewExpression 34
#define EXI_EXIforJS_4_ObjectExpression 35
#define EXI_EXIforJS_4_ObjectPattern 36
#define EXI_EXIforJS_4_Pattern 37
#define EXI_EXIforJS_4_Program 38
#define EXI_EXIforJS_4_Property 39
#define EXI_EXIforJS_4_RegExp 40
#define EXI_EXIforJS_4_ReturnStatement 41
#define EXI_EXIforJS_4_SequenceExpression 42
#define EXI_EXIforJS_4_Statement 43
#define EXI_EXIforJS_4_SwitchCase 44
#define EXI_EXIforJS_4_SwitchStatement 45
#define EXI_EXIforJS_4_ThisExpression 46
#define EXI_EXIforJS_4_ThrowStatement 47
#define EXI_EXIforJS_4_TryStatement 48
#define EXI_EXIforJS_4_UnaryExpression 49
#define EXI_EXIforJS_4_UpdateExpression 50
#define EXI_EXIforJS_4_VariableDeclaration 51
#define EXI_EXIforJS_4_VariableDeclarator 52
#define EXI_EXIforJS_4_WhileStatement 53
#define EXI_EXIforJS_4_WithStatement 54
#define EXI_EXIforJS_4_YieldExpression 55
#define EXI_EXIforJS_4_alternate 56
#define EXI_EXIforJS_4_argument 57
#define EXI_EXIforJS_4_arguments 58
#define EXI_EXIforJS_4_array 59
#define EXI_EXIforJS_4_block 60
#define EXI_EXIforJS_4_body 61
#define EXI_EXIforJS_4_boolean 62
#define EXI_EXIforJS_4_callee 63
#define EXI_EXIforJS_4_cases 64
#define EXI_EXIforJS_4_computed 65
#define EXI_EXIforJS_4_consequent 66
#define EXI_EXIforJS_4_declarations 67
#define EXI_EXIforJS_4_defaults 68
#define EXI_EXIforJS_4_discriminant 69
#define EXI_EXIforJS_4_each 70
#define EXI_EXIforJS_4_elements 71
#define EXI_EXIforJS_4_expression 72
#define EXI_EXIforJS_4_finalizer 73
#define EXI_EXIforJS_4_generator 74
#define EXI_EXIforJS_4_guard 75
#define EXI_EXIforJS_4_guardedHandlers 76
#define EXI_EXIforJS_4_handler 77
#define EXI_EXIforJS_4_id 78
#define EXI_EXIforJS_4_init 79
#define EXI_EXIforJS_4_integer 80
#define EXI_EXIforJS_4_key 81
#define EXI_EXIforJS_4_kind 82
#define EXI_EXIforJS_4_label 83
#define EXI_EXIforJS_4_left 84
#define EXI_EXIforJS_4_lexical 85
#define EXI_EXIforJS_4_name 86
#define EXI_EXIforJS_4_null 87
#define EXI_EXIforJS_4_number 88
#define EXI_EXIforJS_4_object 89
#define EXI_EXIforJS_4_operator 90
#define EXI_EXIforJS_4_param 91
#define EXI_EXIforJS_4_params 92
#define EXI_EXIforJS_4_prefix 93
#define EXI_EXIforJS_4_properties 94
#define EXI_EXIforJS_4_property 95
#define EXI_EXIforJS_4_rest 96
#define EXI_EXIforJS_4_right 97
#define EXI_EXIforJS_4_string 98
#define EXI_EXIforJS_4_test 99
#define EXI_EXIforJS_4_update 100
#define EXI_EXIforJS_4_value 101




/**
 * \brief  	Returns efficient qname (namespaceURI & localName) IDs for qnameID
 *
 * \param       state		   	Codec state
 * \param       qnameID		   	Qualified name ID
 * \param       namespaceURI	QName namespace URI ID
 * \param       localPart		QName local name ID
 * \return                  	Error-Code <> 0
 *
 */
/* int exiEXIforJSGetEQName(exi_state_t* state, uint16_t qnameID, uint16_t* namespaceURI, uint16_t* localPart); */


/**
 * \brief  	Returns qnameIDs for qname namespaceURI & localName
 *
 * \param       state		   	Codec state
 * \param       namespaceURI	QName namespace URI ID
 * \param       localPart		QName local name ID
 * \param       namespaceUriID	QName NamespaceUri ID (out)
 * \param       localNameID		QName LocalName ID (out)
 * \return                  	Error-Code <> 0
 *
 */
/* int exiEXIforJSGetQNameID(exi_state_t* state, uint16_t namespaceURI, uint16_t localPart, uint16_t* qnameID); */
/* int exiEXIforJSGetQNameIDs(exi_state_t* state, uint16_t namespaceURI, uint16_t localPart, uint16_t* namespaceUriID, uint16_t* localNameID); */

/**
 * \brief  	Add  efficient qname (namespaceURI & localName) IDs
 *
 * \param       state		   	Codec state
 * \param       namespaceURI	QName namespace URI ID
 * \param       localPart		QName local name ID
 * \return                  	Error-Code <> 0
 *
 */
int exiEXIforJSAddEQName(exi_state_t* state, size_t namespaceURI, size_t localPart);

#endif

